language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: tutorial-cicd
  api_key:
    secure: nrU/H035KoCPOai65o76Ufg53p3E8j0/wqnEk4dHaONRx9kFfD/mMi5qnMtyd3/CumnknZQLHUC6Ltka6XamdQLLKC8mxtl2k08643pXOaq8FyKsvvKR5jnWQ96L+BsrWtJ8ZDQgtRkwR3GSiH66R6NcFGZpCZR34QFS19dOWwVWhN2d/6Wn6qUCL5/DvDk65zqpBk0gmAe0mt1FLc42RHhB6qG7RSbAimPgLkksRC8NVXFbG3OegoHjm0/nkwq8nFZX/hiv1ud6hoySlzyTLz/D9cgoQpH71loeSLnvAF2hWXN8RajovdHZVsJ4D0vRGtLYp1b8rGbI2tsEPCXYwPEvnxR9PbOHcaXkUe7tNrAWcCUvO0p3YpcyV5Uih51U/+3L/7q2V1beoBSrn7Oy3xRwvzN35n3b6Ro1oDqAmDtXp5zWQyYghV5z8Ie7MRlrmU1Sc+gdkqO2+wsZ13baj8K7Sbli94gGrHqdVUSxjnLPZnc52/VOfVdUN/dJt+3nAgdsRKOQBw7fNCrQgd1Q3TxTvRGerZiEsVpYK+r9nGMcf+z40MIfHMUn0vIGngjVQ7/p/2P9oCHAmv87zU/ca31hYIvEp3M493I768chD8R51Byj9Eut8le1b3LcaXOwKfvAI2rCsOGmK9/CMGzwf25lZoqRE4H/wN4b0+VVekY=
